#!/bin/bash

dotmatch='\./(.+)\.(.+)'
dotbase=''

for file in ./*.*
do
    if [[ $file =~ $dotmatch ]]
    then
        dotbase="${BASH_REMATCH[1]}"

        if [[ -f ~/.$dotbase || -L ~/.$dotbase ]]
        then
            echo "Removing old ~/.$dotbase"
            rm -f ~/.$dotbase
        fi

        ln -s `pwd`/$file ~/.$dotbase
        echo "$dotbase installed."
    fi
done

mv ~/.conkeror-mozrepl ~/.conkeror-mozrepl.js

rm -f ~/.irssi
rm -f ~/.irssi/irssi.config
mkdir ~/.irssi
if [[ -f ~/.irssi/config || -L ~/.irssi/config ]]
then
    echo "Removing old irssi"
    rm -f ~/.irssi/config
fi
ln -s `pwd`/irssi.config ~/.irssi/config
echo "irssi installed."

rm -f ~/.xmonad
mkdir ~/.xmonad
if [[ -f ~/.xmonad/xmonad.hs || -L ~/.xmonad/xmonad.hs ]]
then
    echo "Removing old xmonad"
    rm -f ~/.xmonad/xmonad.hs
fi
ln -s `pwd`/xmonad.hs ~/.xmonad/xmonad.hs
echo "xmonad installed."
