#!/bin/bash

dotmatch='\./(.+)\.(.+)'
dotbase=''

for file in ./*.*
do
    if [[ -f $file ]]
    then
    	if [[ $file =~ $dotmatch ]]
    	then
        	dotbase="${BASH_REMATCH[1]}"

        	if [[ -f ~/.$dotbase || -L ~/.$dotbase ]]
        	then
            		echo "Removing old ~/.$dotbase"
            		rm -f ~/.$dotbase
        	fi

        	cp `pwd`/$file ~/.$dotbase
        	echo "$dotbase installed."
	fi
    fi
done

mv ~/.conkeror-mozrepl ~/.conkeror-mozrepl.js
mv ~/.tmux ~/.tmux.conf

rm -f ~/.irssi
rm -f ~/.irssi/irssi.config
mkdir ~/.irssi
if [[ -f ~/.irssi/config || -L ~/.irssi/config ]]
then
    echo "Removing old irssi"
    rm -f ~/.irssi/config
fi
cp `pwd`/irssi.config ~/.irssi/config
echo "irssi installed."

rm -f ~/.xmonad
mkdir ~/.xmonad
if [[ -f ~/.xmonad/xmonad.hs || -L ~/.xmonad/xmonad.hs ]]
then
    echo "Removing old xmonad"
    rm -f ~/.xmonad/xmonad.hs
fi
cp `pwd`/xmonad.hs ~/.xmonad/xmonad.hs
echo "xmonad installed."

